sonar.projectKey=remio
sonar.organization=aruntejavemula
sonar.projectName=Remio
sonar.sources=frontend/src,backend
sonar.tests=frontend/src,backend/tests
sonar.test.inclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/**/*.spec.ts,frontend/src/**/*.spec.tsx,backend/tests/**/*.py
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/coverage/**,**/dist/**
sonar.coverage.exclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/**/*.spec.ts,frontend/src/**/*.spec.tsx,frontend/src/test/**,frontend/src/main.tsx,frontend/src/sw.ts
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info
