sonar.projectKey=remio
sonar.organization=aruntejavemula
sonar.projectName=Remio
sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**
sonar.python.coverage.reportPaths=coverage.xml
