"""initial schema

Revision ID: 73962bb91a62
Revises: 
Create Date: 2026-05-13 03:36:51.057024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '73962bb91a62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_otps_email'), 'password_reset_otps', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('google_id', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('subscription_status', sa.Enum('active', 'canceled', 'trialing', name='subscriptionstatusenum'), server_default='trialing', nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('secret_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('category', sa.Enum('ai', 'design', 'productivity', 'finance', 'music', name='categoryenum'), nullable=False),
    sa.Column('plan', sa.Enum('paid', 'free', 'trial', name='planenum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manage_url', sa.String(length=2048), nullable=True),
    sa.Column('icon_key', sa.String(length=80), nullable=True),
    sa.Column('frequency', sa.Enum('monthly', 'quarterly', 'yearly', name='billingfrequencyenum'), nullable=True),
    sa.Column('pending_unsubscribe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_is_deleted'), 'apps', ['is_deleted'], unique=False)
    op.create_index('ix_apps_user_display_order', 'apps', ['user_id', 'display_order'], unique=False)
    op.create_index('ix_apps_user_expires_at', 'apps', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_apps_user_id'), 'apps', ['user_id'], unique=False)
    op.create_index('uq_apps_user_slug_active', 'apps', ['user_id', 'slug'], unique=True, postgresql_where=sa.text('NOT is_deleted'))
    op.create_table('preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.Enum('light', 'dark', name='themeenum'), nullable=False),
    sa.Column('start_week_on_monday', sa.Boolean(), nullable=False),
    sa.Column('compact_cards', sa.Boolean(), nullable=False),
    sa.Column('show_last_opened', sa.Boolean(), nullable=False),
    sa.Column('notify_expirations', sa.Boolean(), nullable=False),
    sa.Column('reminder_days', sa.Integer(), nullable=False),
    sa.Column('reminder_email', sa.Boolean(), nullable=False),
    sa.Column('reminder_push', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_user_id'), 'preferences', ['user_id'], unique=True)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'days_before', 'sent_date', name='uq_reminder_log_user_day')
    )
    op.create_index(op.f('ix_reminder_logs_user_id'), 'reminder_logs', ['user_id'], unique=False)
    op.create_table('launch_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("launched_at >= (NOW() - INTERVAL '90 days')", name='ck_launch_events_retention_90d'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_launch_events_app_id'), 'launch_events', ['app_id'], unique=False)
    op.create_index(op.f('ix_launch_events_launched_at'), 'launch_events', ['launched_at'], unique=False)
    op.create_index(op.f('ix_launch_events_user_id'), 'launch_events', ['user_id'], unique=False)
    op.create_index('ix_launch_events_user_launched_at', 'launch_events', ['user_id', sa.literal_column('launched_at DESC')], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('remind_days_before', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('email', 'push', name='remindermethodenum'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('usage_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_sessions_app_id'), 'usage_sessions', ['app_id'], unique=False)
    op.create_index(op.f('ix_usage_sessions_recorded_at'), 'usage_sessions', ['recorded_at'], unique=False)
    op.create_index('ix_usage_sessions_user_app', 'usage_sessions', ['user_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_usage_sessions_user_id'), 'usage_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_sessions_user_id'), table_name='usage_sessions')
    op.drop_index('ix_usage_sessions_user_app', table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_recorded_at'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_app_id'), table_name='usage_sessions')
    op.drop_table('usage_sessions')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_launch_events_user_launched_at', table_name='launch_events')
    op.drop_index(op.f('ix_launch_events_user_id'), table_name='launch_events')
    op.drop_index(op.f('ix_launch_events_launched_at'), table_name='launch_events')
    op.drop_index(op.f('ix_launch_events_app_id'), table_name='launch_events')
    op.drop_table('launch_events')
    op.drop_index(op.f('ix_reminder_logs_user_id'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_preferences_user_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index('uq_apps_user_slug_active', table_name='apps', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('ix_apps_user_id'), table_name='apps')
    op.drop_index('ix_apps_user_expires_at', table_name='apps')
    op.drop_index('ix_apps_user_display_order', table_name='apps')
    op.drop_index(op.f('ix_apps_is_deleted'), table_name='apps')
    op.drop_table('apps')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_password_reset_otps_email'), table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    # ### end Alembic commands ###
